Name:           ros-indigo-apriltags
Version:        0.1.1
Release:        0%{?dist}
Summary:        ROS apriltags package

Group:          Development/Libraries
License:        LGPL
URL:            http://people.csail.mit.edu/kaess/apriltags/
Source0:        %{name}-%{version}.tar.gz

Requires:       eigen3-devel
Requires:       libv4l-devel
Requires:       opencv-devel
BuildRequires:  eigen3-devel
BuildRequires:  libv4l-devel
BuildRequires:  opencv-devel
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-cmake-modules

%description
A catkin version of the C++ apriltags library

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Fri Nov 14 2014 Mitchell Wills <mwills@wpi.edu> - 0.1.1-0
- Autogenerated by Bloom

* Sat Nov 08 2014 Mitchell Wills <mwills@wpi.edu> - 0.1.0-0
- Autogenerated by Bloom

