Name:           ros-hydro-apriltags-ros
Version:        0.0.2
Release:        0%{?dist}
Summary:        ROS apriltags_ros package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/apriltags_ros
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-apriltags
Requires:       ros-hydro-cv-bridge
Requires:       ros-hydro-geometry-msgs
Requires:       ros-hydro-image-transport
Requires:       ros-hydro-message-runtime
Requires:       ros-hydro-nodelet
Requires:       ros-hydro-roscpp
Requires:       ros-hydro-sensor-msgs
Requires:       ros-hydro-std-msgs
Requires:       ros-hydro-tf
BuildRequires:  ros-hydro-apriltags
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-cv-bridge
BuildRequires:  ros-hydro-geometry-msgs
BuildRequires:  ros-hydro-image-transport
BuildRequires:  ros-hydro-message-generation
BuildRequires:  ros-hydro-nodelet
BuildRequires:  ros-hydro-roscpp
BuildRequires:  ros-hydro-sensor-msgs
BuildRequires:  ros-hydro-std-msgs
BuildRequires:  ros-hydro-tf

%description
A package that provides a ROS wrapper for the apriltags C++ package

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Fri Oct 31 2014 Mitchell Wills <mwills@wpi.edu> - 0.0.2-0
- Autogenerated by Bloom

* Tue Oct 28 2014 Mitchell Wills <mwills@wpi.edu> - 0.0.1-0
- Autogenerated by Bloom

